### PR TITLE
draft for projections

### PR DESCRIPTION
**Pull request by harissecic**
Please review, I assume there will be some changes required. Relate to #199

### CODE REVIEW

**Comment by meistermeier** [comment]
I would like to take your addition and restructure it a bit.
Could you please sign our CLA http://neo4j.com/developer/cla/ to take it from here?
Please be careful with the GitHub handle because you used a different one here in contrast to the issue. I just assume that both belong to use.

**Comment by harissecic** [comment]
> I would like to take your addition and restructure it a bit.
> Could you please sign our CLA http://neo4j.com/developer/cla/ to take it from here?
> Please be careful with the GitHub handle because you used a different one here in contrast to the issue. I just assume that both belong to use.

Yeah, I'll use this one (personal harissecic). Thanks. Do I need to do anything more than just send this CLA?

**Comment by meistermeier** [comment]
Looks good, thanks.

**Comment by meistermeier** [comment]
Closed in favour of #233

**Pull request closed without merging**
