### PR TITLE
Extract the PartValidator and share it between imperative and reactive.

### PR DESCRIPTION
**Pull request by michael-simons**
@atomfrede Can you please test if that fixes our issues with JHipster / Reactive? Thx!

### CODE REVIEW

**Comment by atomfrede** [comment]
Sure will do later.

**Comment by michael-simons** [comment]
I'll merge this after we get some feedback from Frederik. Thanks for having a look, Gerrit.

**Comment by atomfrede** [comment]
The thing with the `Instant` seems to work now but still the application doesn't start with following error:

```
Method has to have one of the following return types! [interface java.util.List, interface org.springframework.data.domain.Slice, interface org.springframework.data.domain.Page]
	at org.springframework.data.repository.query.QueryMethod.assertReturnTypeAssignable(QueryMethod.java:307)
	at org.springframework.data.repository.query.QueryMethod.<init>(QueryMethod.java:87)
	at org.neo4j.springframework.data.repository.query.Neo4jQueryMethod.<init>(Neo4jQueryMethod.java:60)
	at org.neo4j.springframework.data.repository.query.ReactiveNeo4jQueryLookupStrategy.resolveQuery(ReactiveNeo4jQueryLookupStrategy.java:62)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.lookupQuery(RepositoryFactorySupport.java:574)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.lambda$mapMethodsToQuery$1(RepositoryFactorySupport.java:567)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Collections$UnmodifiableCollection$1.forEachRemaining(Collections.java:1054)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.mapMethodsToQuery(RepositoryFactorySupport.java:569)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.lambda$new$0(RepositoryFactorySupport.java:559)
	at java.base/java.util.Optional.map(Optional.java:265)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.<init>(RepositoryFactorySupport.java:559)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:332)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$5(RepositoryFactoryBeanSupport.java:297)
	at org.springframework.data.util.Lazy.getNullable(Lazy.java:212)
	at org.springframework.data.util.Lazy.get(Lazy.java:94)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:300)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792)
	... 47 common frames omitted
```
It seems methods with `Pageable` parameter are not yet working. At least to the reactive mongo documentation a query method like `Flux<Person> findByFirstnameOrderByLastname(String firstname, Pageable pageable);` should working. But this is unrelated to this PR imho.

**Comment by atomfrede** [comment]
Was able to reproduce it with the sdn/rx test suite. 

Created a new method in `org.neo4j.springframework.data.integration.reactive.ReactivePersonRepository` like this `	Flux<PersonWithAllConstructor> findAll(Pageable pageable);` and an additonal test in `org.neo4j.springframework.data.integration.reactive.ReactiveRepositoryIT`

```java
	@Test
	void findAllWithPageable() {
		Sort sort = Sort.by("name");
		int page = 0;
		int limit = 1;

		StepVerifier.create(repository.findAll(PageRequest.of(page, limit, sort))).expectNext(person2).verifyComplete();
	}
```

The test fails with the same error message

```
Caused by: java.lang.IllegalStateException: Method has to have one of the following return types! [interface org.springframework.data.domain.Slice, interface java.util.List, interface org.springframework.data.domain.Page]
	at org.springframework.data.repository.query.QueryMethod.assertReturnTypeAssignable(QueryMethod.java:307)
	at org.springframework.data.repository.query.QueryMethod.<init>(QueryMethod.java:87)
	at org.neo4j.springframework.data.repository.query.Neo4jQueryMethod.<init>(Neo4jQueryMethod.java:60)
	at org.neo4j.springframework.data.repository.query.ReactiveNeo4jQueryLookupStrategy.resolveQuery(ReactiveNeo4jQueryLookupStrategy.java:62)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.lookupQuery(RepositoryFactorySupport.java:574)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.lambda$mapMethodsToQuery$1(RepositoryFactorySupport.java:567)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Collections$UnmodifiableCollection$1.forEachRemaining(Collections.java:1054)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.mapMethodsToQuery(RepositoryFactorySupport.java:569)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.lambda$new$0(RepositoryFactorySupport.java:559)
	at java.base/java.util.Optional.map(Optional.java:265)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.<init>(RepositoryFactorySupport.java:559)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:332)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$5(RepositoryFactoryBeanSupport.java:297)
	at org.springframework.data.util.Lazy.getNullable(Lazy.java:212)
	at org.springframework.data.util.Lazy.get(Lazy.java:94)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:300)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1862)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1799)
	... 78 common frames omitted
```

**Comment by meistermeier** [comment]
This is due to the fact that we "just" have one `Neo4jQueryMethod` for imperative and reactive. Looking at Spring Data Mongo there is a special reactive one that overrides the `isStreamQuery` method to be always true (https://github.com/spring-projects/spring-data-mongodb/blob/eacfe2b8f70ae5d4b70aa6c17612825278330400/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/repository/query/ReactiveMongoQueryMethod.java#L159).
Despite this fact the test I wrote for this looks like
```
@Test
void findAllWithPageable() {
	Sort sort = Sort.by("name");
	int page = 0;
	int limit = 1;

	StepVerifier.create(repository.findByName("Test", PageRequest.of(page, limit, sort)))
		.assertNext(person -> assertThat(person).isEqualTo(person1))
		.verifyComplete();
}
```
Because overloading the `findAll` method would also bring in other problems right now.

**Comment by michael-simons** [comment]
> It seems methods with `Pageable` parameter are not yet working. At least to the reactive mongo documentation a query method like `Flux<Person> findByFirstnameOrderByLastname(String firstname, Pageable pageable);`

I wonder that this boots at all. There is no such thing as a paged reactive response, so I wonder about the meaningfulness of `PageRequest` here.

**Pull request merged**
