### PR TITLE
GH-197 - Aggregation functions

### PR DESCRIPTION
**Pull request by romain-rossi**
see #197

### CODE REVIEW

**Comment by romain-rossi** [comment]
Could you please help me with the failed check (https://github.com/neo4j/sdn-rx/pull/198/checks?check_run_id=589011136). 
It seems to be a dependencies resolution issue...
Thanks

**Comment by meistermeier** [comment]
Sorry, this is my fault because after the release of 1.0.0 the mechanism to define the CI-friendly version string got broken. I am currently working on this.

**Comment by meistermeier** [comment]
If you rebase on this branch on the current master, you will also get the latest GitHub actions config with the fixed workflow.

**Comment by romain-rossi** [comment]
Thank you @meistermeier! 
All green :-)

**Comment by michael-simons** [comment]
Thanks so much for your support and work with SDN-RX, @romain-rossi. Highly appreciated and valuable. 

I wanted to do a small (not functional) polishing on your branch beforehand. Would you mind ticking "allow edits from maintainer" the next time you open a PR? That would be lovely and allow us to push into your feature branch. Thanks.

**Comment by romain-rossi** [comment]
You are very welcome @michael-simons 
About "allow edits from maintainer", would it be easier if I recreate the PR with this option? 
I'll do check the option on the next PR for sure.

**Comment by michael-simons** [comment]
All good, next time is perfect. Just wanted to mention it… I didn't know what it does until someone asked me and explained it. It basically gives us edit rights / push rights on your branch of your fork.

**Pull request merged**
